---
- name: Clone the {{ repository_validation_tower_dummy_project_name }} repo
  git:
    repo: "{{ repository_validation_tower_dummy_project_url }}"
    dest: /tmp/{{ repository_validation_tower_dummy_project_name }}
    version: "{{ repository_validation_tower_dummy_project_branch }}"

- name: Copy integreatly dev project to tmp
  shell: cp -rT /var/lib/awx/projects/*ansible_tower_credentials_project /tmp/integreatly_dev

- name: Gathering {{ repository_validation_tower_dummy_project_name }} project variables
  block:
  - include_vars:
      dir: /tmp/{{ repository_validation_tower_dummy_project_name }}/inventories/group_vars/all
      ignore_files:
        - aws_credentials.yml
        - tower.yml
    register: tower_vars
  - set_fact:
      tower_dummy_vars: "{{ tower_vars.ansible_facts | sort}}"
  - copy: 
      content: "{{ tower_dummy_vars }}"
      dest: "/tmp/{{ repository_validation_tower_dummy_project_name }}.yml"

- name: Gathering {{ repository_validation_integreatly_dev_project_name }} project variables
  block:
  - include_vars:
      dir: /tmp/{{ repository_validation_integreatly_dev_project_name }}/inventories/group_vars/all
      ignore_files:
        - aws_credentials.yml
        - tower.yml
    register: integreatly_vars
  - set_fact:
      integreatly_dev_vars: "{{ integreatly_vars.ansible_facts | sort }}"
  - copy: 
      content: "{{ integreatly_dev_vars }}"
      dest: "/tmp/{{ repository_validation_integreatly_dev_project_name }}.yml"

- set_fact:
    differences: "{{ tower_dummy_vars | difference(integreatly_dev_vars) }}"
  register: diff_result

- name: Cleanup tmp directories and files
  file:
      state: absent
      path: "/tmp/{{ item }}"
  with_items:
    - "{{ repository_validation_tower_dummy_project_name }}"
    - "{{ repository_validation_integreatly_dev_project_name }}"
    - "{{ repository_validation_tower_dummy_project_name }}.yml"
    - "{{ repository_validation_integreatly_dev_project_name }}.yml"

- fail:
    msg: "The {{ repository_validation_tower_dummy_project_name }} repository contains the following variables that are not in the {{ repository_validation_integreatly_dev_project_name }} repository: {{ diff_result.ansible_facts.differences }}"
  when: "diff_result.ansible_facts.differences | length != 0"