---
# ansible-vault encrypt_string "admin" --name "username"
# ansible-vault encrypt_string "abcdefghijklmnopqrstuvwxyz" --name "password"
# ansible-playbook --ask-vault-pass ansible_vault_testing.yml
- hosts: localhost
  connection: local
  tasks:
  - name: "Send the integreately POC provisioning email via sendgrid"
    include_role:
      name: sendgrid
      tasks_from: main
